# Site settings
title: William O'Hearn
subtitle: 
email: w.ohearn2@exeter.ac.uk
description: A Personal Researcher Website
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://willotree23.github.io/williamohearn.github.io/" # the base hostname & protocol for your site
author: williamohearn
lang: en_US

# Social settings
github_url: https://willotree23.github.io/williamohearn.github.io

# Build settings
markdown: kramdown

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
